version: "3"
services:
  webserver:
    networks:
      - traefik
      - php
    build: 
      context: docker
      dockerfile: apache.Dockerfile
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./backend/public:/var/www/app/public
    depends_on:
      - app

  app:
    networks:
      - php
      - db
    build: 
      context: docker
      dockerfile: php.Dockerfile
    volumes:
      - ./backend:/var/www/app/
      - php-sessions:/var/lib/php/sessions
    environment:
      - APP_ENV=dev
      - DATABASE_URL="mysql://app:examplePassword@db:3306/app?serverVersion=11.2.2-MariaDB"
    depends_on:
      - db

  db:
    image: mariadb:11.2.2
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: examplePassword
      MYSQL_ROOT_PASSWORD: examplePassword
    volumes:
      - db:/var/lib/mysql
    networks:
      - db

  adminer:
    networks:
      - db
      - traefik
    image: adminer
    environment:
      - ADMINER_DESIGN=nette
      - ADMINER_DEFAULT_SERVER=db
    expose:
      - 8080

volumes:
  php-sessions:
  db:

networks:
  db:
  php:
  traefik:
    #external: true
    name: traefik_default
