version: "3"
services:
  webserver:
    build: 
      context: docker
      dockerfile: apache.Dockerfile
    networks:
      - traefik
      - php
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - ./backend/public:/var/www/app/public
    depends_on:
      - app

  app:
    build: 
      context: docker
      dockerfile: php.Dockerfile
    networks:
      - php
      - db
    volumes:
      - ./backend:/var/www/app/
      - php-sessions:/var/lib/php/sessions
    environment:
      - APP_ENV=dev
      - DATABASE_HOST=db
      - DATABASE_NAME=app
      - DATABASE_USER=app
      - DATABASE_PORT=3306
      - DATABASE_PASS=examplePassword
    depends_on:
      - db

  db:
    image: mariadb:11.2.2
    networks:
      - db
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=app
      - MYSQL_USER=app
      - MYSQL_PASSWORD=examplePassword
      - MYSQL_ROOT_PASSWORD=examplePassword
    volumes:
      - db:/var/lib/mysql

  adminer:
    image: adminer
    networks:
      - db
      - traefik
    environment:
      - ADMINER_DESIGN=nette
      - ADMINER_DEFAULT_SERVER=db
    expose:
      - 8080

volumes:
  php-sessions:
  db:

networks:
  db:
  php:
  traefik:
    #external: true
    name: traefik_default
